import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import ThirdwebProvide from './ThirdwebProvide'
import {StateContextProvider} from './_context'
import createCourse from './_components/createCourse'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  async function connect() {
    if (typeof window.ethereum!="undefined") {
    await ethereum.request({ method: 'eth_requestAccounts'});
    }
}
  return (
    <ClerkProvider>
      <ThirdwebProvide>
        <StateContextProvider>
          <html lang="en">
            <body className={inter.className}>
              {children}

            </body>
          </html>
        </StateContextProvider>
      </ThirdwebProvide>
    </ClerkProvider>
  )
}
